### PR TITLE
Return gateway IP instead of DNS name

### PR DESCRIPTION
**Pull request by ikogan**

### CODE REVIEW

**Comment by ikogan** [comment]
Woops, sorry, I'll take care of those tests tomorrow.

**Comment by francisbrito** [comment]
Hello @ikogan,

Are you still interested in getting this PR merged? It seems the tests broke because of a missing dependency, [this](https://github.com/FGRibreau/network-config/pull/4/files#diff-d886605fd524f6f505fd61ab37a5a9a7R3) in particular. Either adding it to `package.json` or remove the dependency altogether should fix the issue.

If you're too busy and would prefer to have someone else check this out, I'd be glad to take a stab at it. :)

**Comment by danielloczi** [comment]
I think this PR can solve #7. Can you please fix the dependency problem and merge it please?

**Comment by FGRibreau** [comment]
Once the dependency issue is fixed I will merge it. Since this PR is open for too long, don't hesitate to submit another PR ;)

**Pull request closed without merging**
